export const SET_LOCATION_DATA="SET_LOCATION_DATA"
export const GET_WEATHER='GET_WEATHER'
export const WEATHER_DATA_LOADING='WEATHER_DATA_LOADING'
export const SEND_ACCIDENT="SEND_ACCIDENT"
// export const GET
